{
 "title": "Hono",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "TENANT",
    "label": "Tenant",
    "query": "SHOW TAG VALUES WITH KEY = \"tenant\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "content": "<h1 style=\"color:black; background-color:#555555; padding:5px\"><center>Messaging - Telemetry</center></h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "content": "<h1 style=\"color:black; background-color:#555555; padding:5px\"><center>Messaging - Events</center></h1>"
  },
  {
   "title": "Messaging Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"count\") from (SELECT count(value) FROM \"meter.hono.messaging.messages.processed.m1_rate\" where time > now() - 11s group by host)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Processed Telemetry Per Sec (Ø/min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"meter.hono.messaging.messages.processed.m1_rate\" where tenant = '$TENANT' and type = 'telemetry' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Processed Events Per Sec (Ø/min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"meter.hono.messaging.messages.processed.m1_rate\" where tenant = '$TENANT' and type = 'event' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processed Telemetry Per Second (Ø/min)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/meter.hono.server.messages.*.processed.m1_rate/",
     "query": "SELECT mean(value) FROM \"meter.hono.messaging.messages.processed.m1_rate\" WHERE $timeFilter and type = 'telemetry' and  tenant = '$TENANT' GROUP BY host, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processed Events Per Second (Ø/min)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/meter.hono.server.messages.*.processed.m1_rate/",
     "query": "SELECT mean(value) FROM \"meter.hono.messaging.messages.processed.m1_rate\" WHERE $timeFilter and type = 'event' and  tenant = '$TENANT' GROUP BY host, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processed Telemetry",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "meter.hono.server.messages.telemetry/DEFAULT_TENANT.processed.count",
     "query": "select sum(*) from (select last(value) from \"meter.hono.messaging.messages.processed.count\" where tenant = '$TENANT' and type = 'telemetry' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Discarded Telemetry",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "meter.hono.server.messages.telemetry/DEFAULT_TENANT.discarded.count",
     "query": "select sum(*) from ( select last(value) from \"counter.hono.messaging.messages.discarded.count\" where tenant = 'DEFAULT_TENANT' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processed Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "meter.hono.server.messages.telemetry/DEFAULT_TENANT.processed.count",
     "query": "select sum(*) from ( select last(value) from \"meter.hono.messaging.messages.processed.count\" where tenant = '$TENANT' and type = 'event' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Undeliverable Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "meter.hono.server.messages.telemetry/DEFAULT_TENANT.discarded.count",
     "query": "select sum(*) from ( select last(value) from \"counter.hono.messaging.messages.undeliverable.count\" where tenant = 'DEFAULT_TENANT' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
   "content": "<h1 style=\"color:black; background-color:#555555; padding:5px\"><center>MQTT Adapter</center></h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 19 },
   "content": "<h1 style=\"color:black; background-color:#555555; padding:5px\"><center>HTTP Adapter</center></h1>"
  },
  {
   "title": "MQTT Adapter Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"count\") from (SELECT count(value) FROM \"meter.hono.mqtt.messages.processed.count\" where time > now() - 11s group by host)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Processed Telemetry Per Sec (Ø/min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"meter.hono.mqtt.messages.processed.m1_rate\" where tenant = '$TENANT' and type = 'telemetry' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Processed Events Per Sec (Ø/min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"meter.hono.mqtt.messages.processed.m1_rate\" where tenant = '$TENANT' and type = 'event' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Adapter Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"count\") from (SELECT count(value) FROM \"meter.hono.http.messages.processed.count\" where time > now() - 11s group by host)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Processed Telemetry Per Sec (Ø/min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"meter.hono.http.messages.processed.m1_rate\" where tenant = '$TENANT' and type = 'telemetry' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Processed Events Per Sec (Ø/min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"meter.hono.http.messages.processed.m1_rate\" where tenant = '$TENANT' and type = 'event' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processed MQTT Telemetry Per Second (Ø/min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/meter.hono.server.messages.*.processed.m1_rate/",
     "query": "SELECT mean(value) FROM \"meter.hono.mqtt.messages.processed.m1_rate\" WHERE $timeFilter and type = 'telemetry' and  tenant = '$TENANT' GROUP BY host, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processed HTTP Telemetry Per Second (Ø/min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/meter.hono.server.messages.*.processed.m1_rate/",
     "query": "SELECT mean(value) FROM \"meter.hono.http.messages.processed.m1_rate\" WHERE $timeFilter and type = 'telemetry' and  tenant = '$TENANT' GROUP BY host, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processed MQTT Events Per Second (Ø/min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/meter.hono.server.messages.*.processed.m1_rate/",
     "query": "SELECT mean(value) FROM \"meter.hono.mqtt.messages.processed.m1_rate\" WHERE $timeFilter and type = 'event' and  tenant = '$TENANT' GROUP BY host, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processed HTTP Events Per Second (Ø/min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1 Minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/meter.hono.server.messages.*.processed.m1_rate/",
     "query": "SELECT mean(value) FROM \"meter.hono.http.messages.processed.m1_rate\" WHERE $timeFilter and type = 'event' and  tenant = '$TENANT' GROUP BY host, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTT Telemetry Processed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"meter.hono.mqtt.messages.processed.count\" where tenant = '$TENANT' and type = 'telemetry' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTT Telemetry Undeliverable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"counter.hono.mqtt.messages.undeliverable.count\" where tenant = '$TENANT' and type = 'telemetry' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Telemetry Processed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"meter.hono.http.messages.processed.count\" where tenant = '$TENANT' and type = 'telemetry' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Telemetry Undeliverable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"counter.hono.http.messages.undeliverable.count\" where tenant = '$TENANT' and type = 'telemetry' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTT Events Processed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"meter.hono.mqtt.messages.processed.count\" where tenant = '$TENANT' and type = 'event' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTT Events Undeliverable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"counter.hono.mqtt.messages.undeliverable.count\" where tenant = '$TENANT' and type = 'event' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Events Processed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"meter.hono.http.messages.processed.count\" where tenant = '$TENANT' and type = 'event' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Events Undeliverable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from ( select last(value) from \"counter.hono.http.messages.undeliverable.count\" where tenant = '$TENANT' and type = 'event' group by host ) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}