/*******************************************************************************
 * Copyright (c) 2023 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package org.eclipse.hono.service.management.credentials;

import java.util.List;
import java.util.function.Predicate;

/**
 * An X.509 credential type, where authId is generated by applying template to
 * <a href="https://www.ietf.org/rfc/rfc2253.txt">RFC 2253</a> formatted subject DN.
 */
public class X509CertificateCredentialWithGeneratedId extends X509CertificateCredential {

    /**
     * Creates a new credentials object with a generated authentication identifier.
     *
     * @param generatedId The generated authentication identifier.
     * @param secrets The credential's secret(s).
     * @throws NullPointerException if any of the parameters are {@code null}.
     * @throws IllegalArgumentException if secrets is empty.
     */
    protected X509CertificateCredentialWithGeneratedId(final String generatedId,
            final List<X509CertificateSecret> secrets) {
        super(generatedId);
        setSecrets(secrets);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Predicate<String> getAuthIdValidator() {
        return s -> true;
    }
}
