/*******************************************************************************
 * Copyright (c) 2019, 2021 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package org.eclipse.hono.service.management.credentials;

import java.io.ByteArrayInputStream;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

import javax.security.auth.x500.X500Principal;

import org.eclipse.hono.service.management.tenant.Tenant;
import org.eclipse.hono.util.IdentityTemplate;
import org.eclipse.hono.util.RegistryManagementConstants;
import org.eclipse.hono.util.Strings;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonCreator.Mode;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A credential type for storing the <a href="https://www.ietf.org/rfc/rfc2253.txt">RFC 2253</a> formatted subject DN of
 * a client certificate.
 * <p>
 * See <a href="https://www.eclipse.org/hono/docs/api/credentials/#x-509-certificate">X.509 Certificate</a> for an
 * example of the configuration properties for this credential type.
 */
@JsonInclude(value = JsonInclude.Include.NON_NULL)
public class X509CertificateCredential extends CommonCredential {

    static final String TYPE = RegistryManagementConstants.SECRETS_TYPE_X509_CERT;

    private final List<X509CertificateSecret> secrets = new LinkedList<>();
    private final String issuerDN;
    private final String generatedAuthId;

    /**
     * Creates a new credentials object from the given authentication identifier and secrets.
     *
     * @param authId The authentication identifier.
     * @param generatedAuthId The authentication identifier generated by applying the <em>auth-id-template</em>
     *                        from the tenant's trust anchor to the client certificate's subject DN.
     * @param secrets The credential's secret(s).
     * @throws NullPointerException if authentication identifier and secrets are {@code null}.
     */
    protected X509CertificateCredential(final String authId, final String generatedAuthId,
            final List<X509CertificateSecret> secrets) {
        super(authId);
        setSecrets(secrets);
        this.generatedAuthId = generatedAuthId;
        this.issuerDN = null;
    }

    /**
     * Creates a new credentials object for an X.500 Distinguished Name.
     * <p>
     * The given distinguished name will be normalized to RFC 2253 format.
     *
     * @param subjectDN The subject DN of the client certificate to be used as the authentication identifier.
     * @param issuerDN The issuer DN of the client certificate.
     *                 <p> It is used to retrieve the <em>auth-id-template</em> from the tenant's
     *                 trust anchor to generate the authentication identifier.
     * @param generatedAuthId the authentication identifier generated by applying the <em>auth-id-template</em>
     *                        from the tenant's trust anchor to the client certificate's subject DN.
     * @param secrets The credential's secret(s).
     * @throws NullPointerException if subject DN and secrets are {@code null}.
     */
    private X509CertificateCredential(final String subjectDN, final String issuerDN, final String generatedAuthId,
            final List<X509CertificateSecret> secrets) {
        super(new X500Principal(subjectDN).getName(X500Principal.RFC2253));
        setSecrets(secrets);
        this.generatedAuthId = generatedAuthId;
        this.issuerDN = issuerDN;
    }

    /**
     * Creates a new credentials object.
     * <p>
     * This method tries to decode a non-null byte array into an X.509 certificate and delegate to
     * {@link #fromCertificate(X509Certificate, String)}. Otherwise, the
     * {@link #fromSubjectDn(String, String, String, List)} method is invoked with the given
     * subject DN, issuer DN and secrets parameter values.
     *
     * @param derEncodedX509Certificate The DER encoding of the client certificate.
     * @param subjectDN The subject DN of the client certificate to be used as the authentication identifier.
     * @param issuerDN The issuer DN of the client certificate. 
     *                 <p> It is used to retrieve the <em>auth-id-template</em> from the tenant's
     *                 trust anchor to generate the authentication identifier.
     * @param generatedAuthId the authentication identifier generated by applying the <em>auth-id-template</em>
     *                        from the tenant's trust anchor to the client certificate's subject DN.
     * @param secrets The credential's secret(s).
     * @throws NullPointerException if certificate bytes, subject DN and secrets are {@code null}.
     * @throws IllegalArgumentException if the given byte array cannot be decoded into an X.509 certificate or if
     *                                  the given subject and issuer DNs are not a valid X.500 distinguished name or if
     *                                  secrets is empty.
     * @return The credentials.
     */
    @JsonCreator(mode = Mode.PROPERTIES)
    public static X509CertificateCredential fromProperties(
            @JsonProperty(value = RegistryManagementConstants.FIELD_PAYLOAD_CERT) final byte[] derEncodedX509Certificate,
            @JsonProperty(value = RegistryManagementConstants.FIELD_AUTH_ID) final String subjectDN,
            @JsonProperty(value = RegistryManagementConstants.FIELD_ISSUER_DN) final String issuerDN,
            @JsonProperty(value = RegistryManagementConstants.FIELD_GENERATED_AUTH_ID) final String generatedAuthId,
            @JsonProperty(value = RegistryManagementConstants.FIELD_SECRETS) final List<X509CertificateSecret> secrets) {

        if (derEncodedX509Certificate == null) {
            Objects.requireNonNull(subjectDN);
            Objects.requireNonNull(secrets);
            if (secrets.size() != 1) {
                throw new IllegalArgumentException("list must contain exactly one secret");
            }
            return fromSubjectDn(subjectDN, issuerDN, generatedAuthId, secrets);
        } else {
            return fromCertificate(deserialize(derEncodedX509Certificate), generatedAuthId);
        }
    }

    /**
     * Creates a new credentials object from the subject DN and secrets.
     * <p>
     * The given subject DN will be normalized to RFC 2253 format.
     *
     * @param subjectDN The subject DN to use as the authentication identifier.
     * @param secrets The credential's secret(s).
     * @throws NullPointerException if any of the parameters are {@code null}.
     * @throws IllegalArgumentException if the given string is not a valid X.500 distinguished name or if
     *                                  secrets is empty.
     * @return The credentials.
     */
    public static X509CertificateCredential fromSubjectDn(
            final String subjectDN,
            final List<X509CertificateSecret> secrets) {

        return fromSubjectDn(subjectDN, null, null, secrets);
    }

    /**
     * Creates a new credentials object from the subject DN, issuer DN, generated authentication identifier and secrets.
     * <p>
     * The given subject DN and issuer DN will be normalized to RFC 2253 format.
     *
     * @param subjectDN The subject DN to use as the authentication identifier.
     * @param issuerDN The issuer DN of the client certificate.
     *                 <p> It is used to retrieve the <em>auth-id-template</em> from the tenant's
     *                 trust anchor to generate the authentication identifier.
     * @param generatedAuthId the authentication identifier generated by applying the <em>auth-id-template</em>
     *                        from the tenant's trust anchor to the client certificate's subject DN.
     * @param secrets The credential's secret(s).
     * @throws NullPointerException if any of the parameters are {@code null}.
     * @throws IllegalArgumentException if the given subject DN or issuer DN is not a valid X.500
     *                                  distinguished name or if secrets is empty.
     * @return The credentials.
     */
    public static X509CertificateCredential fromSubjectDn(
            final String subjectDN,
            final String issuerDN,
            final String generatedAuthId,
            final List<X509CertificateSecret> secrets) {

        if (Strings.isNullOrEmpty(subjectDN)) {
            throw new IllegalArgumentException("subject DN must not be null or empty");
        }

        final String formattedSubjectDN = new X500Principal(subjectDN).getName(X500Principal.RFC2253);
        return Optional.ofNullable(issuerDN)
                .map(X500Principal::new)
                .map(x500Principal -> x500Principal.getName(X500Principal.RFC2253))
                .map(formattedIssuerDN -> new X509CertificateCredential(formattedSubjectDN, formattedIssuerDN, generatedAuthId, secrets))
                .orElse(new X509CertificateCredential(formattedSubjectDN, null, generatedAuthId, secrets));
    }

    /**
     * Creates a new credentials object.
     *
     * @param certificate The X.509 certificate.
     * @param generatedAuthId the authentication identifier generated by applying the <em>auth-id-template</em>
     *                        from the tenant's trust anchor to the client certificate's subject DN.
     * @return The credentials.
     * @throws NullPointerException if certificate is {@code null}.
     */
    public static X509CertificateCredential fromCertificate(final X509Certificate certificate,
            final String generatedAuthId) {
        Objects.requireNonNull(certificate);

        final var secret = new X509CertificateSecret();
        secret.setNotBefore(certificate.getNotBefore().toInstant());
        secret.setNotAfter(certificate.getNotAfter().toInstant());

        return new X509CertificateCredential(
                certificate.getSubjectX500Principal().getName(X500Principal.RFC2253),
                certificate.getIssuerX500Principal().getName(X500Principal.RFC2253),
                generatedAuthId,
                List.of(secret));
    }

    private static X509Certificate deserialize(final byte[] base64EncodedX509Certificate) {

        try {
            final CertificateFactory factory = CertificateFactory.getInstance("X.509");
            return (X509Certificate) factory.generateCertificate(
                    new ByteArrayInputStream(base64EncodedX509Certificate));
        } catch (final CertificateException e) {
            throw new IllegalArgumentException("cannot deserialize X.509 certificate", e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @JsonIgnore
    public final String getType() {
        return TYPE;
    }

    /**
     * {@inheritDoc}
     *
     * @return An unmodifiable list of secrets.
     */
    @Override
    @JsonProperty(value = RegistryManagementConstants.FIELD_SECRETS)
    public final List<X509CertificateSecret> getSecrets() {
        return Collections.unmodifiableList(secrets);
    }

    /**
     * Sets the list of X509 certificate secrets to use for authenticating a device to protocol adapters.
     * <p>
     * The list cannot be empty and each secret is scoped to the validity period of the certificate.
     *
     * @param secrets The secret to set.
     * @return A reference to this for fluent use.
     * @throws NullPointerException if secrets is {@code null}.
     * @throws IllegalArgumentException if the list of secrets is empty.
     */
    public final X509CertificateCredential setSecrets(final List<X509CertificateSecret> secrets) {
        Objects.requireNonNull(secrets);
        if (secrets.isEmpty()) {
            throw new IllegalArgumentException("secrets cannot be empty");
        }
        this.secrets.clear();
        this.secrets.addAll(secrets);
        return this;
    }

    /**
     * Applies the <em>auth-id-template</em> from the tenant's trust anchor to the client certificate's subject DN.
     * <p>
     * It is only applicable, if a template is configured.
     *
     * @param tenant The tenant information.
     * @return the credential with the generated authentication identifier.
     * @throws NullPointerException if the tenant is {@code null}.
     */
    @JsonIgnore
    public final X509CertificateCredential applyAuthIdTemplate(final Tenant tenant) {
        Objects.requireNonNull(tenant, "tenant information must not be null");

        final String generatedAuthId = Optional.ofNullable(issuerDN)
                .flatMap(tenant::getAuthIdTemplate)
                .map(IdentityTemplate::new)
                .map(t -> t.apply(getAuthId()))
                .orElse(null);
        final X509CertificateCredential credential = new X509CertificateCredential(getAuthId(),
                generatedAuthId, secrets) {

            @Override
            @JsonGetter(value = RegistryManagementConstants.FIELD_GENERATED_AUTH_ID)
            protected String getGeneratedAuthId() {
                return super.getGeneratedAuthId();
            }
        };

        copyCommonAttributesTo(credential);
        return credential;
    }

    /**
     * Overrides the authentication identifier with the generated authentication identifier,
     * if the generated one is not {@code null}.
     *
     * @return The credential with the overridden authentication identifier.
     */
    @JsonIgnore
    public final X509CertificateCredential overrideAuthIdWithGeneratedAuthId() {
        final String authId = Strings.isNullOrEmpty(generatedAuthId) ? getAuthId() : generatedAuthId;
        final X509CertificateCredential credential = new X509CertificateCredential(authId, null, secrets);

        copyCommonAttributesTo(credential);

        return credential;
    }

    /**
     * Gets the authentication identifier generated by applying the <em>auth-id-template</em>
     * from the tenant's trust anchor to the client certificate's subject DN.
     *
     * @return The generated authentication identifier or {@code null}.
     */
    protected String getGeneratedAuthId() {
        return generatedAuthId;
    }

    private void copyCommonAttributesTo(final CommonCredential credential) {
        credential.setComment(getComment());
        credential.setEnabled(isEnabled());
        credential.setExtensions(getExtensions());
    }
}
