trusted-ca.subject-dn=CN=DEFAULT_TENANT_CA,OU=Hono,O=Eclipse IoT,L=Ottawa,C=CA
trusted-ca.public-key=MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEvJKi/cHmU9nW00fynL2+JoHA5FByQp/Xnqf0sE0GEpaDPoy17yOLZYG8DjpRi3iM5yQ6G5D9i6Z0leZP+5Y7S+DN2X89epJFtohw2yVFM2bRhSJlPLvRef6ipMnL/4jj
trusted-ca.algorithm=EC
trusted-ca.not-before=2026-07-15T14:49:59+02:00
trusted-ca.not-after=2027-07-15T14:49:59+02:00
