{
 "title": "Message details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "componentname", "label": "Component Name", "query": "label_values(component_name)" },
   { "name": "tenant", "label": "Tenant", "query": "label_values(tenant)" },
   { "name": "type", "label": "Type", "query": "telemetry,event" },
   { "name": "instance", "label": "Instance", "query": "label_values(host)" }
  ]
 },
 "panels": [
  {
   "title": "Processed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(hono_messages_processed_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__range])",
     "legendFormat": "{{component_name}} - {{type}} - {{host}}"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_processed_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_processed_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_processed_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Processed payload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(hono_messages_processed_payload_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__range])",
     "legendFormat": "{{component_name}} - {{type}} - {{host}}"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_processed_payload_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_processed_payload_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_processed_payload_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(hono_messages_undeliverable_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__range])",
     "legendFormat": "{{component_name}} - {{type}} - {{host}}"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_undeliverable_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))\n/\n(\n  sum(rate(hono_messages_undeliverable_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))\n  +\n  sum(rate(hono_messages_processed_total{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))\n)"
    }
   ]
  }
 ]
}