{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "componentname",
    "label": "Component Name",
    "query": "hono-http,hono-mqtt,hono-amqp,hono-coap"
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "label_values(hono_messages_received_seconds_count,tenant)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Telemetry</span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Events</span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Commands</span>\n</div>"
  },
  {
   "title": "msg/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{type=\"telemetry\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "payload/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(hono_messages_processed_payload_total{type=\"telemetry\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "undel/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(hono_messages_undeliverable_total{type=\"telemetry\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "msg/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{type=\"event\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "payload/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 2 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(hono_messages_processed_payload_total{type=\"event\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "undel/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(hono_messages_undeliverable_total{type=\"event\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "reqs/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(hono_commands_device_delivered_total{component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "resp/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(hono_commands_response_delivered_total{component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "expired/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(hono_commands_ttd_expired_total{component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "msgs/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{type=\"telemetry\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))",
     "legendFormat": "processed"
    },
    {
     "expr": "sum(irate(hono_messages_undeliverable_total{type=\"telemetry\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))",
     "legendFormat": "unprocessed"
    }
   ]
  },
  {
   "title": "msgs/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{type=\"event\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))",
     "legendFormat": "processed"
    },
    {
     "expr": "sum(irate(hono_messages_undeliverable_total{type=\"event\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))",
     "legendFormat": "unprocessed"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_commands_device_delivered_total{component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "payload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_messages_processed_payload_total{type=\"telemetry\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "payload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(hono_messages_processed_payload_total{type=\"event\",component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range])",
     "legendFormat": "{{component_name}} - {{host}}"
    }
   ]
  },
  {
   "title": "Outcome",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_commands_response_delivered_total{component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))",
     "legendFormat": "responses"
    },
    {
     "expr": "sum(irate(hono_commands_ttd_expired_total{component_name=~\"$componentname\",tenant=~\"$tenant\"}[$__range]))",
     "legendFormat": "expired"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (host)(hono_connections_unauthenticated{component_name=~\"$componentname\"}))"
    }
   ]
  }
 ]
}